import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Auto generated sidebar for documentation contents
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
