name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy project on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Add Deploy key with ssh-agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_OF_GITHUB_PAGES_REPOSITORY }}
      
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
          ORGANIZATION_NAME: ${{ github.repository_owner }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME_OF_GITHUB_PAGES_REPOSITORY }}
          DEPLOYMENT_BRANCH: ${{ vars.DEPLOYMENT_BRANCH_OF_GITHUB_PAGES_REPOSITORY }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions at devopsways-ir/docs"
          npm run deploy
